# Generated by Django 3.2.12 on 2023-11-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20231117_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='accessories',
            field=models.ManyToManyField(to='main_app.Accessory'),
        ),
    ]
